config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from scoop.views import home, cat, info, all, product_page, categorya, create

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('cat/', cat, name='cat'),
    path('info/', info, name='info'),
    path('all/', all, name='all'),
    path('categorya/<category_slug>/<pk>/', product_page, name='product_page'),
    path('categorya/<slug>/', categorya, name='categorya'),
    path('create/', create, name='create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

    

scoop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/',blank=True, null=True)

    def __str__(self):
        return self.name
    
    # class Meta:
    #     ordering = ['-id']

class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)   
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-id']

scoop/forms.py
from django import forms
from .models import Product, Category

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'image', 'category']

scoop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product
from .models import Category
from .forms import ProductForm


def home(request):
        categorys = Category.objects.all()
        context = {
        'categorys': categorys,
        }
        return render(request,'scoop/main.html', context)

def cat(request):
    return render(
        request,
        'scoop/cat.html'
    )

def info(request):
    return render(
        request,
        'scoop/info.html'
    )

def all(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'scoop/all.html', context)

def product_page(request, pk, category_slug):
    product = Product.objects.get(id=pk)
    category = Category.objects.get(slug=category_slug)
    context = {
        'product': product,
        'category_slug': category,
    }
    return render(request, 'scoop/product_page.html', context)

def categorya(request, slug): 
     categorya = Category.objects.get(slug=slug)
     products = categorya.product_set.all()
     productss = Product.objects.all()
     context = {
          'categorya': categorya,
          'products': products,
          'productss': productss

     }
     return render(request, 'scoop/categorya.html', context)

def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            Product.objects.create(
                title=cd['title'],
                description=cd['description'],
                price=cd['price'],
                image=cd['image'],
                category=cd['category'],
            )
            return redirect(to='all')
    else:
        form = ProductForm()

    context = {
        'form': form,

    }
    return render(request, 'scoop/create.html', context)

scoop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Main page{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header>
        <div id="head">
            <p class="title">
                Hotspot
                <a href="{% url 'home' %}" id="a1">Категории</a>
                <a href="{% url 'all' %}" id="a2">Все товары</a>
                <a href="{% url 'info' %}" id="a3">О нас</a>
                <a href="{% url 'create' %}" id="a4">Добавить товар</a>
            </p>
        </div>
    </header>
    <div id="logo">
        <div id="log">
            <p id="p1">
                интернет магазин
            </p>
            <p id="p2">
                Hotspot
            </p>
            <p id="p3">
                Низкая цена, высокое качество
            </p>
        </div>
    </div>
    <p></p>
    {% block content %}
    {% endblock %}
    <p></p>
    <footer>
        <p>
            <a href="https://t.me/hotspot_num1"><img src="../static/images/ico/telegram.ico" alt="tico" id="telegram_ico">@hotspot_num1</a>
            <a href="https://youtu.be/dQw4w9WgXcQ"><img src="../static/images/ico/instagram.ico" alt="iico" id="instagram_ico">@hotspot_num1</a>
        </p>
        <p>
            <a href="https://youtu.be/dQw4w9WgXcQ"><img src="../static/images/ico/facebook.ico" alt="fico" id="facebook_ico">@hotspot_shop</a>
            <a href="https://youtu.be/dQw4w9WgXcQ"><img src="../static/images/ico/twitter.ico" alt="tico" id="twitter_ico">@hotspot_sale</a>
        </p>
    </footer>
</body>
</html>

scoop/templates/scoop/all.html
{% extends 'base.html' %}

{% block title %}Все товары{% endblock %}

{% block content %}
    {% for product in products %}
    <a href="{% url 'product_page' product.category.slug product.id %}" id="pr">
        <div class="product">
            <h1>
                {{product.title}}
            </h1>
            <h2>
                {{product.price}} сум
            </h2>
            <img src="{{product.image.url}}" alt="{{product.title}}" id="img-n">
        </div>
    </a>
    {% endfor %}
{% endblock %}

scoop/templates/scoop/cat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cat</title>
    <link rel="stylesheet" href="../../static/css/base.css">
</head>
<body>
    <img src="../../static/images/jpg/38371043_b680f2c86e99.jpg" alt="Это вам, если признаете наш проект лучшим">
</body>
</html>

scoop/templates/scoop/categorya.html
{% extends 'base.html' %}

{% block title %}{{ categorya.name }}{% endblock %}

{% block content %}
    <h1 id="h21">{{ categorya.name }}</h1>
    {% for product in productss %}
        {% if product.category_id == categorya.pk %}
            <a href="{% url 'product_page' product.category.slug product.id %}" id="pr">
                <div class="product">
                    <h1>
                        {{ product.title }}
                    </h1>
                    <h2>
                        {{ product.price }} сум
                    </h2>
                    <img src="{{ product.image.url }}" alt="{{ product.title }}" id="img-n">
                </div>
            </a>
        {% endif %}
    {% endfor %}
{% endblock %}

scoop/templates/scoop/create.html
{% extends 'base.html' %}

{% block title %}Добавить товар{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
                <p>
            <label for="id_title">Title:</label>
            <input type="text" name="title" maxlength="100" required id="id_title">
            
            
        </p>

        
        <p>
            <label for="id_description">Description:</label>
            <textarea name="description" cols="40" rows="10" id="id_description">
        </textarea>
            
            
        </p>

        
        <p>
            <label for="id_price">Price:</label>
            <input type="number" name="price" min="0" required id="id_price">
            
            
        </p>

        
        <p>
            <label for="id_image">Image:</label>
            <input type="file" name="image" accept="image/*" id="id_image">
            
            
        </p>

        
        <p>
            <label for="id_category">Category:</label>
            <select name="category" id="id_category">

        <option value="4" selected>Смартфоны</option>

        <option value="5">Видеокарты</option>

        <option value="6">Мониторы</option>

        <option value="7">Компьютеры</option>

        </select>
            
            
            
            
        </p>
        <input type="submit" value="Creat">
    </form>
{% endblock %}

scoop/templates/scoop/info.html
{% extends 'base.html' %}

{% block title %}О нас{% endblock %}

{% block content %}
<div id="info">
    <h1>О нас</h1>
    <p>Мы рады приветствовать вас в интернет-магазине Hotspot!</p>
    <p>Hotspot - это магазин, который предлагает широкий ассортимент товаров по низким ценам и высокому качеству. Мы стремимся удовлетворить потребности наших клиентов, предлагая только лучшие товары.</p>
    <p>Магазин Hotspot был открыт в 2010 году двумя братьями, Максимом и Александром Ивановыми. Они разделяют общую страсть к технологиям и решили создать магазин, где каждый сможет найти необходимые товары по доступным ценам.</p>
    <p>Наш магазин предлагает широкий выбор электроники, компьютеров, мобильных устройств, бытовой техники и многое другое. Мы тщательно отбираем товары, чтобы убедиться, что они соответствуют нашим стандартам качества.</p>
    <p>Мы гордимся нашим отличным обслуживанием клиентов. Наша команда всегда готова помочь вам с выбором товара, ответить на ваши вопросы и обеспечить приятный опыт покупок.</p>
    <p>Благодарим вас за выбор магазина Hotspot! Мы надеемся, что вы останетесь довольны нашими услугами и продуктами.</p>
    <p>Сайт сделан лушими програмистами мира.</p>
</div>
{% endblock %}

scoop/templates/scoop/main.html
{% extends 'base.html' %}

{% block title %}Hotspot{% endblock %}

{% block content %}
    {% for category in categorys %}
    <a href="{% url 'categorya' category.slug %}" id="aaa">
        <div class="cat">
            <h1>{{category.name}}</h1>
            <img src="{{category.image.url}}" alt="{{category.name}}" id="img-c">
        </div>
    </a>
    {% endfor %}
{% endblock %}

scoop/templates/scoop/product_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{product.title}}</title>
    <link rel="stylesheet" href="../../../static/css/base.css">
</head>
<body>
    <header>
        <div id="head">
            <p class="title">
                Hotspot
                <a href="{% url 'home' %}" id="a1">Категории</a>
                <a href="{% url 'all' %}" id="a2">Все товары</a>
                <a href="{% url 'info' %}" id="a3">О нас</a>
                <a href="{% url 'cat' %}" id="a4">Учителю Атабек</a>
            </p>
        </div>
    </header>
    <div id="logo">
        <div id="log">
            <p id="p1">
                интернет магазин
            </p>
            <p id="p2">
                Hotspot
            </p>
            <p id="p3">
                Низкая цена, высокое качество
            </p>
        </div>
    </div>
    <p></p>

<div class="pwrt">
    <h1>
        {{product.title}}
    </h1>
    <img src="{{product.image.url}}" alt="{{product.title}}" id="img-n">
    <h2>
        {{product.price}} сум
    </h2>
    <br><br>
    <h1>Описание</h1>
    <p>{{product.description}}</p>
    <button id="b1">В корзину</button>
</div>

<p></p>
<footer>
    <p>
        <a href="https://t.me/hotspot_num1"><img src="../../../static/images/ico/telegram.ico" alt="tico" id="telegram_ico">@hotspot_num1</a>
        <a href="https://youtu.be/dQw4w9WgXcQ"><img src="../../../static/images/ico/instagram.ico" alt="iico" id="instagram_ico">@hotspot_num1</a>
    </p>
    <p>
        <a href="https://youtu.be/dQw4w9WgXcQ"><img src="../../../static/images/ico/facebook.ico" alt="fico" id="facebook_ico">@hotspot_shop</a>
        <a href="https://youtu.be/dQw4w9WgXcQ"><img src="../../../static/images/ico/twitter.ico" alt="tico" id="twitter_ico">@hotspot_sale</a>
    </p>
</footer>
</body>
</html>